[General]
;General Basic options

logPrefix=test-
;logPrefix Prefix to use for log entries.
;logPrefix Type: Text
;logPrefix Default: debug-

enableLogging=0
;enableLogging Check this box to enable logging for debugging.
;enableLogging CheckboxName: Enable logging for debug purposes
;enableLogging Type: Checkbox
;enableLogging Default: 1

language=English
;language Choose the language for the application's interface.
;language Type: DropDown English|Spanish|French
;language Default: French

[FilePaths]
;FilePaths File picker options

configFile=D:\testing\asubfolder\info.txt
;configFile Path to the configuration file for the application.
;configFile Type: File
;configFile Default: C:\Users\Example\config.ini

outputFolder=F:\testing\another folder with spaces\._\test
;outputFolder Default folder where files will be saved.
;outputFolder Type: Folder
;outputFolder Default: C:\Users\Example\Documents\Output

[Numerical]
;Numerical Number settings. Only allow number (and decimal) input.

maxThreads=24
;maxThreads Set the maximum number of threads the application can use (Integer - Whole number only).
;maxThreads Type: Integer
;maxThreads Default: 4

threadLoad=45.789415234896324432
;threadLoad Type: Float
;threadLoad Default: 32.5
;threadLoad Set the maximum load per thread the application can use (Float - Includes decimal).

[HotkeySettings]
;HotkeySettings Hotkey settings. Inputs will be stored as entered, including modifiers.

openAppHotkey=+^o
;openAppHotkey Define the hotkey combination to open the application.
;openAppHotkey Type: Hotkey
;openAppHotkey Default: ^+o

[DateTimeSettings]
;DateTimeSettings Date and Time settings. Note that the stored value will be a full/long datetime no matter what.

eventDate=20250205010525
;eventDate Set the custom date for an application event.
;eventDate Default: 20250205010525
;eventDate Type: DateTime

eventShortDate=20250905000000
;eventShortDate Set the custom date for an application event.
;eventShortDate Default: 20250101
;eventShortDate Type: DateTime ShortDate

eventTime=19700101090530
;eventTime Set the custom time for an application event.
;eventTime Default: 19700101070530
;eventTime Type: DateTime Time

[HiddenSettings]
;HiddenSettings Settings that will only be accessible in the INI file. You could explain more about them here in this box, so they know what to look for when they open the file.

debugMode=0
;debugMode Enable or disable debug mode (hidden from the UI).
;debugMode Hidden:
